### ISSUE TITLE
OpenAI error: The model: `gpt-4` does not exist > Is it possible to run the narrator with gpt-3.5-turbo?

### ISSUE THREAD

**Issue by hugo4711** [ingig/code-narrator#5]
The code-narrator crashes when one does not have access to gpt-4 via the API

```
Starting code-narrator
Understanding project and auto generating code-narrator.config.js
OpenAI error: The model: `gpt-4` does not exist
```

**Comment by ingig** [comment]
You can use -g argument when running to set model to gtp-3.5-turbo, see https://github.com/ingig/code-narrator/blob/master/docs/howto/HowTo%20run%20CLI.md

**Comment by ingig** [comment]
@hugo4711 I have updated the library to fall back to gpt-3.5-turbo if gpt-4 is not available. 

The results are not so nice, so not sure if it is a good idea :)

**Comment by hugo4711** [comment]
Thanks! It works - and yeah: 3.5 results in regards to code is mediocre in comparison to GPT-4. I hope we will have access to the API soon.
